StudentApp/StudentApp/Controllers/ProfileAdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudentApp.Filters;
using StudentApp.Models;
using StudentApp.ViewModels.Admin;

namespace StudentApp.Controllers
{
    [Isconnected]
    public class ProfileAdminController : Controller
    {
        private readonly U669885128UZsNtContext _context;
        public ProfileAdminController(U669885128UZsNtContext context)
        {
            this._context = context;
        }


        [ActionName("ProfileSimpleAdmin")]
        public IActionResult ProfileSimpleAdmin()
        {
            Admin admin = _context.Admins.FirstOrDefault(u => u.Id == int.Parse(HttpContext.Session.GetString("Id")));
            return View(admin);
        }

        
        [ActionName("ProfileSettingsAdmin")]
        public IActionResult ProfileSettingsAdmin()
        {
            Admin admin = _context.Admins.FirstOrDefault(u => u.Id == int.Parse(HttpContext.Session.GetString("Id")));
            ProfileSettingsAdminVM profile = new ProfileSettingsAdminVM();
            profile.Prenom = admin.Prenom;
            profile.Nom = admin.Nom;
            profile.Email = admin.Email;
            return View(profile);
        }


   
        [ActionName("ProfileSettingsAdmin")]
        [HttpPost]
        public IActionResult ProfileSettingsAdmin(ProfileSettingsAdminVM newAdmin)
        {
            if (ModelState.IsValid)
            {
                Admin admin = _context.Admins.FirstOrDefault(u => u.Id == int.Parse(HttpContext.Session.GetString("Id")));
                admin.Prenom = newAdmin.Prenom;
                admin.Nom = newAdmin.Nom;
                admin.Email = newAdmin.Email;
                _context.SaveChanges();
                HttpContext.Session.SetString("Nom", newAdmin.Nom);
                HttpContext.Session.SetString("Prenom", newAdmin.Prenom);
                return RedirectToAction(nameof(ProfileSimpleAdmin));
            }
            return View(newAdmin);
        }


        [HttpPost]
        public IActionResult UpdatePasswordAdmin(string oldpassword, string newpassword, string confirmpassword)
        {
            if (oldpassword == null)
            {
                return Json(new { success = false, error = 5 });
            }
            if (newpassword == null)
            {
                return Json(new { success = false, error = 6 });
            }
            if (confirmpassword == null)
            {
                return Json(new { success = false, error = 7 });
            }

            if (newpassword.Length < 4)
            {
                return Json(new { success = false, error = 4 });
            }

            if (newpassword == oldpassword)
            {
                return Json(new { success = false, error = 1 });
            }

            if (newpassword != confirmpassword)
            {
                return Json(new { success = false, error = 2 });
            }

            Admin admin = _context.Admins.FirstOrDefault(u => u.Id == int.Parse(HttpContext.Session.GetString("Id")));
            if (admin != null)
            {
                if (admin.Password == oldpassword)
                {
                    admin.Password = newpassword;
                    _context.SaveChanges();
                    return Json(new { success = true });
                }
                else
                {
                    return Json(new { success = false, error = 3 });
                }
            }

            return Json(new { success = false, error = 4 });
        }

        /*

        [Isconnected(Role = "Client")]
        [HttpPost]
        public IActionResult UpdateCoverClient(IFormFile cover)
        {
            Client client = _context.Clients.FirstOrDefault(a => a.Id == int.Parse(HttpContext.Session.GetString("Id")));
            if (client != null)
            {
                string fileName = $"{DateTime.Now:yyyyMMddHHmmss}-{"@@"}-{cover.Length}-{cover.FileName}";
                string result = VerificationImage.VerifierCover(cover, fileName);

                if (result == "true")
                {
                    VerificationImage.UpdateImage(client.Cover);
                    client.Cover = fileName;
                    _context.SaveChanges();
                    return Json(new { success = true, message = "Le cover a été Modifier avec succès." });
                }
                else
                {
                    return Json(new { success = false, message = result });
                }
            }

            return Json(new { success = false, message = "client nexist pas." });
        }


        [Isconnected(Role = "Client")]
        [HttpPost]
        public IActionResult UpdatePhotoClient(IFormFile photo)
        {
            Client client = _context.Clients.FirstOrDefault(a => a.Id == int.Parse(HttpContext.Session.GetString("Id")));
            if (client != null)
            {
                string fileName = $"{DateTime.Now:yyyyMMddHHmmss}-{"@@"}-{photo.Length}-{photo.FileName}";
                string result = VerificationImage.VerifierImage(photo, fileName);

                if (result == "true")
                {
                    VerificationImage.UpdateImage(client.Cover);
                    client.Photo = fileName;
                    _context.SaveChanges();
                    HttpContext.Session.SetString("Photo", client.Photo);
                    return Json(new { success = true, message = "La Photo a été Modifier avec succès." });
                }
                else
                {
                    return Json(new { success = false, message = result });
                }
            }

            return Json(new { success = false, message = "Client nexist pas." });
        }


        */

    }
}

StudentApp/StudentApp/Views/ProfileAdmin/ProfileSimpleAdmin.cshtml
@{
    ViewBag.Title = "Profile";
    Layout = null;
}

@model Admin

<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="disable">
<head>
    @Html.Partial("~/Views/Shared/_title_meta.cshtml")

    <!-- swiper css -->
    <link rel="stylesheet" href="~/assets/libs/swiper/swiper-bundle.min.css">

    @Html.Partial("~/Views/Shared/_head_css.cshtml")
</head>
<body>
    <!-- Begin page -->
    <div id="layout-wrapper">
        @Html.Partial("~/Views/Shared/_menu.cshtml")

        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="container-fluid">
                    <div class="profile-foreground position-relative mx-n4 mt-n4">
                        <div class="profile-wid-bg">
                            <img src="~/userImages/client.png" alt="" class="profile-wid-img" />
                        </div>
                    </div>
                    <div class="pt-4 mb-4 mb-lg-3 pb-lg-4">
                        <div class="row g-4">
                            <div class="col-auto">
                                <div class="avatar-lg">
                                    <img src='~/userImages/client.png' alt="user-img"
                                         class="img-thumbnail rounded-circle" />
                                </div>
                            </div>
                            <!--end col-->
                            <div class="col">
                                <div class="p-2">
                                    <h3 class="text-white mb-1">@Model.Nom @Model.Prenom</h3>
                                    <p class="text-white text-opacity-75">Ltrack Admin</p>
                                </div>
                            </div>
                            <!--end col-->
                        </div>
                        <!--end row-->
                    </div>

                    <div class="row">
                        <div class="col-lg-12">
                            <div>
                                <div class="d-flex">
                                    <!-- Nav tabs -->
                                    <ul class="nav nav-pills animation-nav profile-nav gap-2 gap-lg-3 flex-grow-1"
                                        role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link fs-14 active" data-bs-toggle="tab" href="#overview-tab"
                                               role="tab">
                                                <i class="ri-airplay-fill d-inline-block d-md-none"></i> <span class="d-none d-md-inline-block">Aperçu</span>
                                            </a>
                                        </li>
                                    </ul>
                                    <div class="flex-shrink-0">
                                        <a href="@Url.Action("ProfileSettingsAdmin", "ProfileAdmin")" class="btn btn-success">
                                            <i class="ri-edit-box-line align-bottom"></i> Modifier le profile
                                        </a>
                                    </div>
                                </div>
                                <!-- Tab panes -->
                                <div class="tab-content pt-4 text-muted">
                                    <div class="tab-pane active" id="overview-tab" role="tabpanel">
                                        <div class="row">
                                            <div class="col-xxl-3">
                                                <div class="card">
                                                    <div class="card-body">
                                                        <h5 class="card-title mb-3">Information</h5>
                                                        <div class="table-responsive">
                                                            <table class="table table-borderless mb-0">
                                                                <tbody>
                                                                    <tr>
                                                                        <th class="ps-0" scope="row">Nom :</th>
                                                                        <td class="text-muted">@Model.Nom</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <th class="ps-0" scope="row">Prenom :</th>
                                                                        <td class="text-muted">@Model.Prenom</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <th class="ps-0" scope="row">E-mail :</th>
                                                                        <td class="text-muted">@Model.Email</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <th class="ps-0" scope="row">Profile :</th>
                                                                        <td class="text-muted">Lytrack Admin</td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div><!-- end card body -->
                                                </div><!-- end card -->

                                            </div>
                                            <!--end col-->
                                            <div class="col-xxl-9">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="card">
                                                            <div class="card-header align-items-center d-flex">
                                                                <h4 class="card-title mb-0  me-2">LYTRACK STUDENT MANAGEMENT</h4>
                                                            </div>
                                                            <div class="card-body">
                                                                <div class="tab-content text-muted">
                                                                    <div class="tab-pane active" id="today"
                                                                         role="tabpanel">
                                                                        <div class="profile-timeline">
                                                                            <div class="accordion accordion-flush"
                                                                                 id="todayExample">
                                                                                <div class="accordion-item border-0">
                                                                                    <div id="collapseOne"
                                                                                         class="accordion-collapse collapse show"
                                                                                         aria-labelledby="headingOne"
                                                                                         data-bs-parent="#accordionExample">
                                                                                        <div class="accordion-body ms-2 ps-5">
                                                                                            Rationalisez la gestion des étudiants avec LYTRACK STUDENT MANAGEMENT
                                                                                            Dans le monde dynamique de l’éducation, une gestion efficace des étudiants est primordiale pour favoriser un environnement d’apprentissage prospère. LYTRACK STUDENT MANAGEMENT apparaît comme votre solution complète, permettant aux établissements de gérer de manière transparente tous les aspects de la vie étudiante.
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <!--end accordion-->
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div><!-- end card body -->
                                                        </div><!-- end card -->
                                                    </div><!-- end col -->
                                                </div><!-- end row -->
                                            </div>
                                            <!--end col-->
                                        </div>
                                        <!--end row-->
                                    </div>
                                </div>
                                <!--end tab-content-->
                            </div>
                        </div>
                        <!--end col-->
                    </div>
                    <!--end row-->

                </div>
                <!-- container-fluid -->
            </div><!-- End Page-content -->
            @Html.Partial("~/Views/Shared/_footer.cshtml")
        </div>

    </div>
    <!-- END layout-wrapper -->
    @Html.Partial("~/Views/Shared/_customizer.cshtml")

    @Html.Partial("~/Views/Shared/_vendor_scripts.cshtml")

    <!-- swiper js -->
    <script src="~/assets/libs/swiper/swiper-bundle.min.js"></script>

    <!-- profile init js -->
    <script src="~/assets/js/pages/profile.init.js"></script>

    <!-- App js -->
    <script src="~/assets/js/app.js"></script>
</body>
</html>