StudentApp/StudentApp/Models/AdType.cs
using System;
using System.Collections.Generic;

namespace StudentApp.Models;

public partial class AdType
{
    public int Id { get; set; }

    public string Libelle { get; set; } = null!;

    public virtual ICollection<Campaign> Campaigns { get; set; } = new List<Campaign>();
}

StudentApp/StudentApp/ViewModels/Ads/AjouterAdVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using StudentApp.Models;
using System.ComponentModel.DataAnnotations;

namespace StudentApp.ViewModels.Ads
{

    public enum Os
    {
        Ios,
        Android,
        Windows
    }
    public class AjouterAdVM
    {
        [Display(Name = "Date de début")]
        [Required(ErrorMessage = "La date de début est requise.")]
        public DateTime DateDebut { get; set; }

        [Display(Name = "Date de fin")]
        [Required(ErrorMessage = "La date de fin est requise.")]
        public DateTime DateFin { get; set; }

        [Display(Name = "Budget")]
        [Required(ErrorMessage = "Le budget est requis.")]
        [Range(0, double.MaxValue, ErrorMessage = "Le budget doit être supérieur ou égal à zéro.")]
        public double Budget { get; set; }

        [Display(Name = "URL du contenu")]
        [Required(ErrorMessage = "L'URL du contenu est requise.")]
        [Url(ErrorMessage = "L'URL du contenu n'est pas valide.")]
        public string ContentUrl { get; set; }

        [Display(Name = "URL de l'annonce")]
        [Required(ErrorMessage = "L'URL de l'annonce est requise.")]
        [Url(ErrorMessage = "L'URL de l'annonce n'est pas valide.")]
        public string AdUrl { get; set; }

        [Display(Name = "Type d'annonce")]
        [Required(ErrorMessage = "Le type d'annonce est requis.")]
        public int IdType { get; set; }

        [Display(Name = "Éditeur")]
        [Required(ErrorMessage = "L'éditeur est requis.")]
        public int IdPublisher { get; set; }

        [Display(Name = "Tranche d'âge")]
        [Required(ErrorMessage = "La tranche d'âge est requise.")]
        public int IdAgeRange { get; set; }

        [Display(Name = "Localisation")]
        [Required(ErrorMessage = "La localisation est requise.")]
        public int IdLocation { get; set; }

        public List<SelectListItem>? ageRanges { get; set; } = null!;

        public List<SelectListItem>? locations  { get; set; } = null!;

        public List<SelectListItem>? publishers { get; set; } = null!;

        public List<SelectListItem>? types { get; set; } = null!;
        public List<O>? Os { get; set; } = null!;
        [Required(ErrorMessage = "Os is required.")]
        public List<int> oschoix { get; set; }
    }
}

StudentApp/StudentApp/Controllers/AdsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentApp.Filters;
using StudentApp.Models;
using StudentApp.ViewModels.Ads;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using static Twilio.Rest.Content.V1.ContentResource;

namespace StudentApp.Controllers
{
    [Isconnected]
    public class AdsController : Controller
    {
        private readonly U669885128UZsNtContext _context;
        public AdsController(U669885128UZsNtContext context)
        {
            this._context = context;
        }


        public IActionResult Index()
        {
            var adsWithAllData = _context.Campaigns
            .Include(c => c.Clicks)
            .Include(c => c.IdAgeRangeNavigation)
            .Include(c => c.IdLocationNavigation)
            .Include(c => c.IdPublisherNavigation)
            .Include(c => c.IdTypeNavigation)
            .Include(c => c.CampainOs)
            .ThenInclude(c => c.IdOsNavigation)
            .ToList();
            return View(adsWithAllData);
        }


        public IActionResult AjouterAd()
        {
            AjouterAdVM ad = new AjouterAdVM();

            List<AgeRange> ranges = _context.AgeRanges.ToList();
            List<Location> Locations = _context.Locations.ToList();
            List<Publisher> publishers = _context.Publishers.ToList();
            List<AdType> AdTypes = _context.AdTypes.ToList();
            ad.Os = _context.Os.ToList();

            ad.ageRanges = ranges.Select(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = r.Max.ToString() + " - "+ r.Min.ToString() 
            }).ToList();

            ad.locations = Locations.Select(l => new SelectListItem
            {
                Value = l.Id.ToString(), 
                Text = l.Libelle
            }).ToList();

            
            ad.publishers = publishers.Select(p => new SelectListItem
            {
                Value = p.Id.ToString(), 
                Text = p.Name 
            }).ToList();

          
            ad.types = AdTypes.Select(t => new SelectListItem
            {
                Value = t.Id.ToString(), 
                Text = t.Libelle
            }).ToList();

             



            return View(ad);
        }


        [HttpPost]
        public IActionResult AjouterAd(AjouterAdVM ad)
        {
            if (ad.DateDebut < DateTime.Now)
            {
                ModelState.AddModelError("DateDebut", "La date de début ne peut pas être dans le passé.");
            }

            if (ad.DateDebut > ad.DateFin)
            {
                ModelState.AddModelError("DateFin", "La date de fin doit être superieur à la date de debut.");
            }

            


            if (ModelState.IsValid)
            {
                
                try
                {
                    
                    _context.Database.BeginTransaction();
                    Campaign cam = new Campaign();
                    cam.DateDebut = ad.DateDebut;
                    cam.DateFin = ad.DateFin;
                    cam.Budget = ad.Budget;
                    cam.ContentUrl = ad.ContentUrl;
                    cam.AdUrl = ad.AdUrl;
                    cam.IdType = ad.IdType;
                    cam.IdPublisher = ad.IdPublisher;
                    cam.IdAgeRange = ad.IdAgeRange;
                    cam.IdLocation = ad.IdLocation;

                    _context.Campaigns.Add(cam);
                    _context.SaveChanges();

                    foreach (var os in ad.oschoix)
                    {
                        CampainO campainOs = new CampainO();
                        campainOs.IdCampaign = cam.Id;
                        campainOs.IdOs = os;
                        _context.CampainOs.Add(campainOs);
                    }
                    _context.SaveChanges();
                    _context.Database.CommitTransaction();


                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    _context.Database.RollbackTransaction();
                }
            }


            List<AgeRange> ranges = _context.AgeRanges.ToList();
            List<Location> Locations = _context.Locations.ToList();
            List<Publisher> publishers = _context.Publishers.ToList();
            List<AdType> AdTypes = _context.AdTypes.ToList();
            ad.Os = _context.Os.ToList();

            ad.ageRanges = ranges.Select(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = r.Max.ToString() + " - " + r.Min.ToString()
            }).ToList();

            ad.locations = Locations.Select(l => new SelectListItem
            {
                Value = l.Id.ToString(),
                Text = l.Libelle
            }).ToList();


            ad.publishers = publishers.Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.Name
            }).ToList();


            ad.types = AdTypes.Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Libelle
            }).ToList();

            return View(ad);
        }


        public IActionResult removeAd(int Id)
        {
            Campaign c = _context.Campaigns.FirstOrDefault(c => c.Id == Id);
            if (c != null)
            {
                _context.Campaigns.Remove(c);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }
            



    }
}

StudentApp/StudentApp/Views/Ads/AjouterAd.cshtml
@using StudentApp.ViewModels.Ads
@{
    ViewBag.Title = "Ajouter Campagnes publicitaires";
    ViewBag.pTitle = "Ajouter Campagnes publicitaires";
    ViewBag.pageTitle = "Lytrack";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model AjouterAdVM


@section styles {
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
}

<form method="post">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="live-preview">
                        <div class="row gy-4">
                            <div class="col-xxl-3 col-md-6">
                                <div>
                                    <label asp-for="DateDebut" class="form-label">Date Debut</label>
                                    <input asp-for="DateDebut" class="form-control" placeholder="Date Debut"><br />
                                    <span asp-validation-for="DateDebut" class="text-danger"></span><br />
                                </div>
                            </div>
                            <!--end col-->
                            <div class="col-xxl-3 col-md-6">

                                <div>
                                    <label asp-for="DateFin" class="form-label">Date Fin</label>
                                    <input asp-for="DateFin" class="form-control" placeholder="Date Fin"><br />
                                    <span asp-validation-for="DateFin" class="text-danger"></span>
                                </div>
                            </div>
                            <!--end col-->
                            <div class="col-xxl-3 col-md-6">
                                <div>
                                    <label asp-for="Budget" class="form-label">Budget</label>
                                    <input asp-for="Budget" class="form-control" placeholder="Budget"><br />
                                    <span asp-validation-for="Budget" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <!--end row-->
                        <div>
                            <div class="row g-3">
                                <div class="col-lg-6">
                                    <label asp-for="ContentUrl" class="form-label">URL du contenu</label>
                                    <div class="input-group">
                                        <span class="input-group-text"
                                              id="basic-addon3">https://example.com/...</span>
                                        <input asp-for="ContentUrl" type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br />
                                    </div>
                                    <span asp-validation-for="ContentUrl" class="text-danger"></span>
                                </div>
                                <div class="col-lg-6">
                                    <label asp-for="AdUrl" class="form-label">URL de l'annonce</label>
                                    <div class="input-group">
                                        <span class="input-group-text"
                                              id="basic-addon3">https://example.com/...</span>
                                        <input asp-for="AdUrl" type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3"><br />
                                    </div>
                                    <span asp-validation-for="AdUrl" class="text-danger"></span>
                                </div>
                            </div>
                        </div><br />
                        <!--end row-->
                        <div class="vstack gap-3">
                            <label asp-for="IdType" class="form-label">Type Campaign</label>
                            <select asp-for="IdType" asp-items="@Model.types" class="js-example-disabled" required>
                                <option value="AL">Choisir Type</option>
                            </select>
                            <span asp-validation-for="IdType" class="text-danger"></span>

                            <label asp-for="IdPublisher" class="form-label">Éditeur</label>
                            <select asp-for="IdPublisher" asp-items="@Model.publishers" class="js-example-disabled" required>
                                <option value="AL">Choisir L'Éditeur'</option>
                            </select>
                            <span asp-validation-for="IdPublisher" class="text-danger"></span>

                            <label asp-for="IdAgeRange" class="form-label">Tranche d'âge</label>
                            <select asp-for="IdAgeRange" asp-items="@Model.ageRanges" class="js-example-disabled" required>
                                <option value="AL">Choisir Tranche d'âge</option>
                            </select>
                            <span asp-validation-for="IdAgeRange" class="text-danger"></span>

                            <label asp-for="IdLocation" class="form-label">Locliation</label>
                            <select asp-for="IdLocation" asp-items="@Model.locations" class="js-example-disabled" required>
                                <option value="AL">Choisir Localition</option>
                            </select>
                            <span asp-validation-for="IdLocation" class="text-danger"></span>
                        </div><br />
                        <!--end row-->
                        <div class="row">
                            <div class="col-md-6">
                                <div>
                                    <label for="DateDebut" class="form-label">système d'exploitation</label>
                                    <div>
                                        @foreach (var plateform in Model.Os)
                                        {
                                            <div class="asp-form-check mb-3">
                                                <input name="oschoix" value="@plateform.Id" class="form-check-input" type="checkbox" id="asp-formCheck6">
                                                <label class="form-check-label">
                                                    @plateform.Libelle
                                                </label>
                                            </div>
                                        }
                                        <span asp-validation-for="oschoix" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div><br />
                        <!--end row-->
                        
                        <div class="row g-3">
                            <div class="col-lg-6">
                                @*
                                <label asp-for="DateDebut" class="form-label">Importer Image or Video</label>
                                <div class="input-group">
                                    <input type="file" class="form-control" id="inputGroupFile04"
                                           aria-describedby="inputGroupFileAddon04"
                                           aria-label="Upload">
                                    <button class="btn btn-outline-success" type="button"
                                            id="inputGroupFileAddon04">
                                        Button
                                    </button>
                                </div><br />
                                *@
                                <div class="hstack gap-2 mt-3">
                                    <button type="submit" class="js-programmatic-enable btn btn-success">
                                        Ajouter
                                    </button>
                                    <a asp-controller="Ads" asp-action="Index" type="button" class="btn btn-danger">
                                        Annuler
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--end col-->
    </div>
</form>




@section scripts {
    <!-- prismjs plugin -->

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!--select2 cdn-->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script src="~/assets/js/pages/select2.init.js"></script>


    <script src="~/assets/libs/prismjs/prism.js"></script>
    <script src="~/assets/js/app.js"></script>
}

StudentApp/StudentApp/Views/Ads/Index.cshtml
@using StudentApp.ViewModels
@{
    ViewBag.Title = "Campagnes publicitaires";
    Layout = null;
}

@model IList<Campaign>
<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg" data-sidebar-image="none" data-preloader="disable">
<head>
    @Html.Partial("~/Views/Shared/_title_meta.cshtml")

    <!-- swiper css -->
    <link rel="stylesheet" href="~/assets/libs/swiper/swiper-bundle.min.css">

    @Html.Partial("~/Views/Shared/_head_css.cshtml")
</head>
<body>
    <!-- Begin page -->
    <div id="layout-wrapper">
        @Html.Partial("~/Views/Shared/_menu.cshtml")

        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">


                <h3>Gestion des Campagnes publicitaires </h3>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            @*
                            <div class="card-header">
                                <h4 class="card-title mb-0">Add, Edit & Remove</h4>
                            </div><!-- end card header -->
                            *@
                            <div class="card-body">
                                <div id="customerList">
                                    <div class="row g-4 mb-3">
                                        <div class="col-sm-auto">
                                            <div>
                                                <a asp-controller="Ads" asp-action="AjouterAd" class="btn btn-success add-btn" ><i class="ri-add-line align-bottom me-1"></i> Ajouter</a>
                                                @*<button class="btn btn-soft-danger" onClick="deleteMultiple()"><i class="ri-delete-bin-2-line"></i></button>*@
                                            </div>
                                        </div>
                                        <div class="col-sm">
                                            <div class="d-flex justify-content-sm-end">
                                                <div class="search-box ms-2">
                                                    <input type="text" class="form-control search" placeholder="Recherche...">
                                                    <i class="ri-search-line search-icon"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="table-responsive table-card mt-3 mb-1">
                                        <table class="table align-middle table-nowrap">
                                            <thead class="table-light">
                                                <tr>
                                                    
                                                    <th class="sort" data-sort="Date_debut">Date_debut</th>
                                                    <th class="sort" data-sort="Date_Fin">Date Fin</th>
                                                    <th class="sort" data-sort="Budget">Budget</th>
                                                    <th class="sort" data-sort="content_url">URL du contenu</th>
                                                    <th class="sort" data-sort=" ad_url">URL de l'annonce</th>
                                                    <th class="sort" data-sort="type">Type</th>
                                                    <th class="sort" data-sort="publisher">Éditeur</th>
                                                    <th class="sort" data-sort="age_range">Tranche d'âge</th>
                                                    <th class="sort" data-sort="Location">Localisation</th>
                                                    <th class="sort" data-sort="Location">Système</th>
                                                    <th class="sort" data-sort="action">Action</th>
                                                </tr>
                                            </thead>

                                            <tbody class="list form-check-all">
                                                @foreach (var Ad in Model)
                                                {
                                                    <tr>
                                                        <td class="id" style="display:none;"><a href="javascript:void(0);" class="fw-medium link-primary">@Ad.Id</a></td>
                                                        <td class="nom">@Ad.DateDebut.ToString("dd/MM/yyyy") - @Ad.DateDebut.ToString("HH:mm")</td>
                                                        <td class="prenom">@Ad.DateFin.ToString("dd/MM/yyyy") - @Ad.DateFin.ToString("HH:mm")</td>
                                                        <td class="cen">@Ad.Budget</td>
                                                        <td class="cin">@Ad.ContentUrl</td>
                                                        <td class="tel">@Ad.AdUrl</td>
                                                        <td class="adresse">@Ad.IdTypeNavigation.Libelle</td>
                                                        <td class="email">@Ad.IdPublisherNavigation.Name</td>
                                                        <td class="email">@Ad.IdAgeRangeNavigation.Min - @Ad.IdAgeRangeNavigation.Max </td>
                                                        <td class="email">@Ad.IdLocationNavigation.Libelle</td>
                                                        <td class="email">
                                                            <ul>
                                                                @foreach (var os in Ad.CampainOs)
                                                                {
                                                                    <li>@os.IdOsNavigation.Libelle</li>
                                                                }
                                                            </ul>
                                                        </td>   
                                                        <td>
                                                            <div class="d-flex gap-2">
                                                                <div class="edit">
                                                                    <button onclick="updateAd(@Ad.Id)" class="btn btn-sm btn-success edit-item-btn"
                                                                            data-bs-toggle="modal" data-bs-target="#showModal">
                                                                        Modifier
                                                                    </button>
                                                                </div>
                                                                <div class="remove">
                                                                    <button class="btn btn-sm btn-danger remove-item-btn" onclick="removeAd(@Ad.Id)" data-bs-toggle="modal" data-bs-target="#deleteRecordModal">Supprimer</button>
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                        <div class="noresult" style="display: none">
                                            <div class="text-center">
                                                <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="loop"
                                                           colors="primary:#121331,secondary:#08a88a" style="width:75px;height:75px">
                                                </lord-icon>
                                                <h5 class="mt-2">Sorry! No Result Found</h5>
                                                <p class="text-muted mb-0">
                                                    We've searched more than 150+ Orders We did not find any
                                                    orders for you search.
                                                </p>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="d-flex justify-content-end">
                                        <div class="pagination-wrap hstack gap-2">
                                            <a class="page-item pagination-prev disabled" href="#">
                                                précédent
                                            </a>
                                            <ul class="pagination listjs-pagination mb-0"></ul>
                                            <a class="page-item pagination-next" href="#">
                                                Suivant
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- end card -->
                        </div>
                        <!-- end col -->
                    </div>
                    <!-- end col -->
                </div>
                <!-- end row -->
                <!-- Modal -->
                <div class="modal fade zoomIn" id="deleteRecordModal" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="btn-close"></button>
                            </div>
                            <div class="modal-body">
                                <div class="mt-2 text-center">
                                    <lord-icon src="https://cdn.lordicon.com/gsqxdxog.json" trigger="loop"
                                               colors="primary:#f7b84b,secondary:#f06548" style="width:100px;height:100px"></lord-icon>
                                    <div class="mt-4 pt-2 fs-15 mx-4 mx-sm-5">
                                        <h4>Es-tu sûr ?</h4>
                                        <p class="text-muted mx-4 mb-0">Êtes-vous sûr de vouloir supprimer cet enregistrement ?</p>
                                    </div>
                                </div>
                                <div class="d-flex gap-2 justify-content-center mt-4 mb-2">
                                    <button type="button" class="btn w-sm btn-light" data-bs-dismiss="modal">Annuler</button>
                                    <button type="button" onclick="redirectto()" class="btn w-sm btn-danger" id="delete-record">Supprimer</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--end modal -->
                
            </div><!-- End Page-content -->
            @Html.Partial("~/Views/Shared/_footer.cshtml")
        </div>

    </div>
    <!-- END layout-wrapper -->
    @Html.Partial("~/Views/Shared/_customizer.cshtml")

    @Html.Partial("~/Views/Shared/_vendor_scripts.cshtml")


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>

        let AdsId = 0;

        function removeAd(AdId) {

            AdsId = AdId
        }

        function redirectto() {
            window.location.href = "/Ads/removeAd/" + AdsId;
        }

    </script>


    <!-- swiper js -->
    <script src="~/assets/libs/swiper/swiper-bundle.min.js"></script>

    <!-- profile init js -->
    <script src="~/assets/js/pages/profile.init.js"></script>

    <!-- App js -->
    <script src="~/assets/js/app.js"></script>


    <!-- prismjs plugin -->
    <script src="~/assets/libs/prismjs/prism.js"></script>
    <script src="~/assets/libs/list.js/list.min.js"></script>
    <script src="~/assets/libs/list.pagination.js/list.pagination.min.js"></script>

    <!-- listjs init -->
    <script src="~/assets/js/pages/listjs.init.js"></script>

    <!-- Sweet Alerts js -->
    <script src="~/assets/libs/sweetalert2/sweetalert2.min.js"></script> 

 
</body>
</html>