StudentApp/StudentApp/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using StudentApp.Models;
using StudentApp.ViewModels;
using StudentApp.ViewModels.Admin;

namespace StudentApp.Controllers
{
    public class AuthenticationController : Controller
    {
        U669885128UZsNtContext Context { get; set; }

        public AuthenticationController(U669885128UZsNtContext Context)
        {
            this.Context = Context;
        }
        

        [ActionName("SignInBasic")]
        public IActionResult SignInBasic()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignInBasic(LoginVM userViewModel)
        {
            if (ModelState.IsValid)
            {

                Admin admin = Context.Admins.FirstOrDefault(u => u.Email == userViewModel.email.ToLower() &&  u.Password == userViewModel.Password);
                if (admin is not null )
                {
                    HttpContext.Session.SetString("Id", admin.Id.ToString());
                    HttpContext.Session.SetString("Nom", admin.Nom);
                    HttpContext.Session.SetString("Email", admin.Email);
                    HttpContext.Session.SetString("Prenom", admin.Prenom);
                    HttpContext.Session.SetString("Role", "Admin");
                    return RedirectToAction("Analytics", "Dashboard1");
                }
                else
                {
                    ViewBag.utilisateurExist = "";
                } 
            }
            return View();
        }



        [ActionName("LogoutBasic")]
        public IActionResult LogoutBasic()
        {
            HttpContext.Session.Clear();
            return View();
        }


        [ActionName("LockScreenBasic")]
        public IActionResult LockScreenBasic()
        {
            HttpContext.Session.Remove("Id");
            return View();
        }


        [ActionName("LockScreenBasic")]
        [HttpPost]
        public IActionResult LockScreenBasic(LockScreenVM adminvm)
        {
            if (ModelState.IsValid)
            {

                Admin admin = Context.Admins.FirstOrDefault(u => u.Email == HttpContext.Session.GetString("Email").ToLower() && u.Password == adminvm.Password);
                if (admin is not null)
                {
                    HttpContext.Session.SetString("Id", admin.Id.ToString());
                    HttpContext.Session.SetString("Nom", admin.Nom);
                    HttpContext.Session.SetString("Prenom", admin.Prenom);
                    HttpContext.Session.SetString("Email", admin.Email);
                    HttpContext.Session.SetString("Role", "Admin");
                    return RedirectToAction("Analytics", "Dashboard1");
                }
                else
                {
                    ViewBag.utilisateurExist = "";
                }
            }
            return View();
        }



        [ActionName("PasswordChangeBasic")]
        public IActionResult PasswordChangeBasic()
        {
            return View();
        }

        [ActionName("PasswordChangeCover")]
        public IActionResult PasswordChangeCover()
        {
            return View();
        }

        [ActionName("PasswordResetBasic")]
        public IActionResult PasswordResetBasic()
        {
            return View();
        }

        [ActionName("PasswordResetCover")]
        public IActionResult PasswordResetCover()
        {
            return View();
        }

        

        [ActionName("LockScreenCover")]
        public IActionResult LockScreenCover()
        {
            return View();
        }

        

        [ActionName("LogoutCover")]
        public IActionResult LogoutCover()
        {
            return View();
        }

        [ActionName("SuccessMessageBasic")]
        public IActionResult SuccessMessageBasic()
        {
            return View();
        }

        [ActionName("SuccessMessageCover")]
        public IActionResult SuccessMessageCover()
        {
            return View();
        }

        [ActionName("TwoStepVerificationBasic")]
        public IActionResult TwoStepVerificationBasic()
        {
            return View();
        }

        [ActionName("TwoStepVerificationCover")]
        public IActionResult TwoStepVerificationCover()
        {
            return View();
        }

        [ActionName("Offline")]
        public IActionResult Offline()
        {
            return View();
        }

    }
}

StudentApp/StudentApp/Views/Authentication/LockScreenBasic.cshtml
@using StudentApp.ViewModels.Admin
@{
    ViewBag.Title = "Écran verrouillé";
    Layout = null;
}

@model LockScreenVM

<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="ladylip" data-sidebar-size="lg">

<head>
    @Html.Partial("~/Views/Shared/_title_meta.cshtml")
    @Html.Partial("~/Views/Shared/_head_css.cshtml")
</head>
<body>

    <div class="auth-page-wrapper pt-5">
        <!-- auth page bg -->
        <div class="auth-one-bg-position auth-one-bg" id="auth-particles">
            <div class="bg-overlay"></div>

            <div class="shape">
                <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1440 120">
                    <path d="M 0,36 C 144,53.6 432,123.2 720,124 C 1008,124.8 1296,56.8 1440,40L1440 140L0 140z"></path>
                </svg>
            </div>
        </div>

        <!-- auth page content -->
        <div class="auth-page-content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center mt-sm-5 mb-4 text-white-50">
                            <div>
                                <a href="@Url.Action("Analytics", "Dashboard1")" class="d-inline-block auth-logo">
                                    <img src="~/assets/images/logo lytrack1.png" alt="" height="70">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->

                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6 col-xl-5">
                        <div class="card mt-4">

                            <div class="card-body p-4">
                                <div class="text-center mt-2">
                                    <h5 class="text-primary">Écran verrouillé</h5>
                                    <p class="text-muted">Entrez votre mot de passe pour déverrouiller l'écran !</p>
                                </div>
                                <div class="user-thumb text-center">
                                    <img src="~/userImages/client.png" class="rounded-circle img-thumbnail avatar-lg" alt="thumbnail">
                                    <h5 class="font-size-15 mt-3">@Context.Session.GetString("Nom") @Context.Session.GetString("Prenom")</h5>
                                </div>
                                <div class="p-2 mt-4">
                                    <form method="post">
                                        @if (ViewBag.utilisateurExist != null)
                                        {
                                            <div id="errorMessage" class="alert alert-danger" role="alert">
                                                <span class="text-danger">le mot de passe est incorrect.</span>
                                            </div>

                                        }
                                        <div class="mb-3">
                                            <label class="form-label" asp-for="Password">Mot de pass</label>
                                            <input asp-for="Password" type="password" class="form-control" id="userpassword" placeholder="Mot de pass" required>
                                            <span asp-validation-for="Password" class="text-danger"></span>
                                        </div>
                                        <div class="mb-2 mt-4">
                                            <button class="btn btn-success w-100" type="submit">Ouvrir</button>
                                        </div>
                                    </form><!-- end form -->

                                </div>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card -->

                        <div class="mt-4 text-center">
                            <p class="mb-0">Ce n'est pas vous ? Revenez à la page de <a href="@Url.Action("SignInBasic", "Authentication")" class="fw-semibold text-primary text-decoration-underline"> connexion </a> </p>
                        </div>

                    </div>
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->
        <!-- footer -->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center">
                            <p class="mb-0 text-muted">&copy;
                            <script>document.write(new Date().getFullYear())</script> Lytrack <i class="mdi mdi-heart text-danger"></i></p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->
    </div>
    <!-- end auth-page-wrapper -->

    @Html.Partial("~/Views/Shared/_vendor_scripts.cshtml")

    <!-- particles js -->
    <script src="~/assets/libs/particles.js/particles.js"></script>
    <!-- particles app js -->
    <script src="~/assets/js/pages/particles.app.js"></script>

</body>
</html>

StudentApp/StudentApp/Views/Authentication/LockScreenCover.cshtml
@{
    ViewBag.Title = "Écran verrouillé";
    Layout = null;
}

<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="ladylip" data-sidebar-size="lg">
<head>
    @Html.Partial("~/Views/Shared/_title_meta.cshtml")
    @Html.Partial("~/Views/Shared/_head_css.cshtml")
</head>
<body>

    <!-- auth-page wrapper -->
    <div class="auth-page-wrapper auth-bg-cover py-5 d-flex justify-content-center align-items-center min-vh-100">
        <div class="bg-overlay"></div>
        <!-- auth-page content -->
        <div class="auth-page-content overflow-hidden pt-lg-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card overflow-hidden">
                            <div class="row justify-content-center g-0">
                                <div class="col-lg-6">
                                    <div class="p-lg-5 p-4 auth-one-bg h-100">
                                        <div class="bg-overlay"></div>
                                        <div class="position-relative h-100 d-flex flex-column">
                                            <div class="mb-4">
                                                <a href="@Url.Action("Index", "Dashboard")" class="d-block">
                                                    <img src="~/assets/images/logo-light.png" alt="" height="18">
                                                </a>
                                            </div>
                                            <div class="mt-auto">
                                                <div class="mb-3">
                                                    <i class="ri-double-quotes-l display-4 text-success"></i>
                                                </div>

                                                <div id="qoutescarouselIndicators" class="carousel slide" data-bs-ride="carousel">
                                                    <div class="carousel-indicators">
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="0" class="active"
                                                                aria-current="true" aria-label="Slide 1"></button>
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="1"
                                                                aria-label="Slide 2"></button>
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="2"
                                                                aria-label="Slide 3"></button>
                                                    </div>
                                                    <div class="carousel-inner text-center text-white pb-5">
                                                        <div class="carousel-item active">
                                                            <p class="fs-15 fst-italic">" Great! Clean code, clean design, easy for customization. Thanks very much! "</p>
                                                        </div>
                                                        <div class="carousel-item">
                                                            <p class="fs-15 fst-italic">" The theme is really great with an amazing customer support."</p>
                                                        </div>
                                                        <div class="carousel-item">
                                                            <p class="fs-15 fst-italic">" Great! Clean code, clean design, easy for customization. Thanks very much! "</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- end carousel -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end col -->

                                <div class="col-lg-6">
                                    <div class="p-lg-5 p-4">
                                        <div>
                                            <h4 class="text-primary">Lock Screen</h4>
                                            <p class="text-muted">Enter your password to unlock the screen!</p>
                                        </div>
                                        <div class="user-thumb text-center">
                                            <img src="~/assets/images/users/avatar-1.jpg" class="rounded-circle img-thumbnail avatar-lg" alt="thumbnail">
                                            <h5 class="mt-3">Anna Adame</h5>
                                        </div>

                                        <div class="mt-4">
                                            <form>
                                                <div class="mb-3">
                                                    <label class="form-label" for="userpassword">Password</label>
                                                    <input type="password" class="form-control" id="userpassword" placeholder="Enter password" required>
                                                </div>
                                                <div class="mb-2 mt-4">
                                                    <button class="btn btn-success w-100" type="submit">Unlock</button>
                                                </div>
                                            </form><!-- end form -->
                                        </div>

                                        <div class="mt-5 text-center">
                                            <p class="mb-0">Not you ? return <a href="@Url.Action("SignInCover", "Authentication")" class="fw-semibold text-primary text-decoration-underline"> Signin</a></p>
                                        </div>
                                    </div>
                                </div>
                                <!-- end col -->
                            </div>
                            <!-- end row -->
                        </div>
                        <!-- end card -->
                    </div>
                    <!-- end col -->

                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->
        <!-- footer -->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center">
                            <p class="mb-0">&copy;
                            <script>document.write(new Date().getFullYear())</script> Velzon. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->
    </div>
    <!-- end auth-page-wrapper -->

    @Html.Partial("~/Views/Shared/_vendor_scripts.cshtml")

</body>
</html>

StudentApp/StudentApp/Views/Authentication/LogoutBasic.cshtml
@{
    ViewBag.Title = "Se déconnecter";
    Layout = null;
}

<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="ladylip" data-sidebar-size="lg">
<head>
    @Html.Partial("~/Views/Shared/_title_meta.cshtml")
    @Html.Partial("~/Views/Shared/_head_css.cshtml")
</head>
<body>

    <div class="auth-page-wrapper pt-5">
        <!-- auth page bg -->
        <div class="auth-one-bg-position auth-one-bg" id="auth-particles">
            <div class="bg-overlay"></div>

            <div class="shape">
                <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1440 120">
                    <path d="M 0,36 C 144,53.6 432,123.2 720,124 C 1008,124.8 1296,56.8 1440,40L1440 140L0 140z"></path>
                </svg>
            </div>
        </div>

        <!-- auth page content -->
        <div class="auth-page-content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center mt-sm-5 mb-4 text-white-50">
                            <div>
                                <a href="@Url.Action("Analytics", "Dashboard1")" class="d-inline-block auth-logo">
                                    <img src="~/assets/images/logo lytrack1.png" alt="" height="70">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end row -->

                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6 col-xl-5">
                        <div class="card mt-4">
                            <div class="card-body p-4 text-center">
                                <lord-icon src="https://cdn.lordicon.com/hzomhqxz.json"
                                           trigger="loop"
                                           colors="primary:#405189,secondary:#08a88a"
                                           style="width:180px;height:180px">
                                </lord-icon>

                                <div class="mt-4 pt-2">
                                    <h4>
                                        Vous êtes déconnecté
                                    </h4>
                                    <p class="text-muted">Merci d'avoir utilisé le modèle <span class="fw-bold">Lytrack</span> d'administration.</p>
                                    <div class="mt-4">
                                        <a href="@Url.Action("SignInBasic", "Authentication")" class="btn btn-success w-100">Se Connecter</a>
                                    </div>
                                </div>
                            </div>
                            <!-- end card body -->
                        </div>
                        <!-- end card -->

                    </div>
                    <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->
        <!-- footer -->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center">
                            <p class="mb-0 text-muted">&copy;
                            <script>document.write(new Date().getFullYear())</script> Lytrack. <i class="mdi mdi-heart text-danger"></i></p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->
    </div>
    <!-- end auth-page-wrapper -->

    @Html.Partial("~/Views/Shared/_vendor_scripts.cshtml")

    <!-- particles js -->
    <script src="~/assets/libs/particles.js/particles.js"></script>

    <!-- particles app js -->
    <script src="~/assets/js/pages/particles.app.js"></script>

</body>
</html>

StudentApp/StudentApp/Views/Authentication/LogoutCover.cshtml
@{
    ViewBag.Title = "Log Out";
    Layout = null;
}

<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="ladylip" data-sidebar-size="lg">
<head>
    @Html.Partial("~/Views/Shared/_title_meta.cshtml")
    @Html.Partial("~/Views/Shared/_head_css.cshtml")
</head>
<body>

    <!-- auth-page wrapper -->
    <div class="auth-page-wrapper auth-bg-cover py-5 d-flex justify-content-center align-items-center min-vh-100">
        <div class="bg-overlay"></div>
        <!-- auth-page content -->
        <div class="auth-page-content overflow-hidden pt-lg-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card overflow-hidden">
                            <div class="row justify-content-center g-0">
                                <div class="col-lg-6">
                                    <div class="p-lg-5 p-4 auth-one-bg h-100">
                                        <div class="bg-overlay"></div>
                                        <div class="position-relative h-100 d-flex flex-column">
                                            <div class="mb-4">
                                                <a href="@Url.Action("Index", "Dashboard")" class="d-block">
                                                    <img src="~/assets/images/logo-light.png" alt="" height="18">
                                                </a>
                                            </div>
                                            <div class="mt-auto">
                                                <div class="mb-3">
                                                    <i class="ri-double-quotes-l display-4 text-success"></i>
                                                </div>

                                                <div id="qoutescarouselIndicators" class="carousel slide" data-bs-ride="carousel">
                                                    <div class="carousel-indicators">
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="0" class="active"
                                                                aria-current="true" aria-label="Slide 1"></button>
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="1"
                                                                aria-label="Slide 2"></button>
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="2"
                                                                aria-label="Slide 3"></button>
                                                    </div>
                                                    <div class="carousel-inner text-center text-white pb-5">
                                                        <div class="carousel-item active">
                                                            <p class="fs-15 fst-italic">" Great! Clean code, clean design, easy for customization. Thanks very much! "</p>
                                                        </div>
                                                        <div class="carousel-item">
                                                            <p class="fs-15 fst-italic">" The theme is really great with an amazing customer support."</p>
                                                        </div>
                                                        <div class="carousel-item">
                                                            <p class="fs-15 fst-italic">" Great! Clean code, clean design, easy for customization. Thanks very much! "</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- end carousel -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end col -->

                                <div class="col-lg-6">
                                    <div class="p-lg-5 p-4 text-center">
                                        <lord-icon src="https://cdn.lordicon.com/hzomhqxz.json"
                                                   trigger="loop"
                                                   colors="primary:#405189,secondary:#08a88a"
                                                   style="width:180px;height:180px">
                                        </lord-icon>

                                        <div class="mt-4 pt-2">
                                            <h4>You are Logged Out</h4>
                                            <p class="text-muted">Thank you for using <span class="fw-bold">velzon</span> admin template</p>
                                            <div class="mt-4">
                                                <a href="@Url.Action("SignInBasic", "Authentication")" class="btn btn-success w-100">Sign In</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end col -->
                            </div>
                            <!-- end row -->
                        </div>
                        <!-- end card -->
                    </div>
                    <!-- end col -->

                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->
        <!-- footer -->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center">
                            <p class="mb-0">&copy;
                            <script>document.write(new Date().getFullYear())</script> Velzon. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->
    </div>
    <!-- end auth-page-wrapper -->

    @Html.Partial("~/Views/Shared/_vendor_scripts.cshtml")

</body>
</html>

StudentApp/StudentApp/Views/Authentication/Offline.cshtml
@{
    ViewBag.Title = "Offline Page";
    Layout = null;
}

<!doctype html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="ladylip" data-sidebar-size="lg">
<head>
    @Html.Partial("~/Views/Shared/_title_meta.cshtml")
    @Html.Partial("~/Views/Shared/_head_css.cshtml")
</head>
<body>

    <!-- auth-page wrapper -->
    <div class="auth-page-wrapper auth-bg-cover py-5 d-flex justify-content-center align-items-center min-vh-100">
        <div class="bg-overlay"></div>
        <!-- auth-page content -->
        <div class="auth-page-content overflow-hidden pt-lg-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-5">
                        <div class="card overflow-hidden">
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <img src="https://img.themesbrand.com/velzon/images/auth-offline.gif" alt="" height="210">
                                    <h3 class="mt-4 fw-semibold">We're currently offline</h3>
                                    <p class="text-muted mb-4 fs-14">We can't show you this images because you aren't connected to the internet. When you’re back online refresh the page or hit the button below</p>
                                    <button class="btn btn-success btn-border" onClick="window.location.href=window.location.href"><i class="ri-refresh-line align-bottom"></i> Refresh</button>
                                </div>
                            </div>
                        </div>
                        <!-- end card -->
                    </div>
                    <!-- end col -->

                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->
    </div>
    <!-- end auth-page-wrapper -->

</body>
</html>